FROM node:14

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copy the package.json and package-lock.json
COPY package*.json ./

# Install production dependencies.
RUN npm install

# Copy the rest of the application code
COPY src/ ./src
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./
COPY .eslintrc.js ./

# Build the NestJS application
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Run the application
CMD ["npm", "run", "start:prod"]