FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY src/ ./src
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./
COPY .eslintrc.js ./
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start:prod"]